### ISSUE TITLE
后台标签数据表改造

### ISSUE THREAD

**Issue by biggeng** [OCSP/OCSP_mainline#1]
当前的数据库中，STREAM_LABEL表用来存储标签和流作业的关系，例如：某个作业需要打的标签。这种组织形式不利于统计所有的标签。
需要改造的内容如下：
1. 拆分STREAM_LABEL表，另外创建一个表label用来存储当前系统的所有标签，标签来源于导入的标签jar包。
2. STREAM_LABEL表变为存储标签和流作业的关系表。用来表示标签和作业的关系，将标签类，标签名等列放到1中的新建的表中。
3. 根据改造后的数据表，修改相应的后端代码。

**Comment by biggeng** [comment]
请 @DoraemonXX 处理这个问题，并更新数据字典。

**Comment by DoraemonXX** [comment]
增加表STREAM_LABEL_DEFINITION，结构如下
![2016-11-04 4 33 54](https://cloud.githubusercontent.com/assets/21124194/19999320/92ec71d2-a2ac-11e6-8923-55c1b980ce37.png)
原STREAM_LABEL表去掉name，class_name列并增加label_id列
此问题涉及修改的文件：TableInfoConstant.scala，DataInterfaceServer.scala

@biggeng @GalvinYang 
Please review the changes, thanks.

[DataInterfaceServer.scala.diff](https://github.com/OCSP/OCSP_mainline/files/570957/DataInterfaceServer.scala.diff.txt)
[TableInfoConstant.scala.diff](https://github.com/OCSP/OCSP_mainline/files/570958/TableInfoConstant.scala.diff.txt)

**Comment by DoraemonXX** [comment]
Fixed

**Comment by DoraemonXX** [comment]
将STREAM_LABEL中的properties字段移到STREAM_LABEL_DEFINITION中。
