### ISSUE TITLE
清理core代码中的过量注释

### ISSUE THREAD

**Issue by biggeng** [OCSP/OCSP_mainline#10]
现在代码中有大量的注释，严重影响了代码的阅读性，需要清楚这些注释。

**Comment by DoraemonXX** [comment]
@YangJie9 
Please handle it, thanks

**Comment by YangJie9** [comment]
1.com.asiainfo.ocdp.stream.subject 这个包貌似没啥用；
2.修改掉的注释如下： @DoraemonXX @biggeng [a.txt](https://github.com/OCSP/OCSP_mainline/files/633248/a.txt)

**Comment by DoraemonXX** [comment]
@YangJie9 
OK for me, please go ahead and if no any references to classes in subject package remove them .

**Comment by YangJie9** [comment]
subject package 用到了，是我看错了，所以没动，现在就是把其他的注释去掉了。

**Comment by DoraemonXX** [comment]
Fixed
