### ISSUE TITLE
[Bug]输入源不应该是公有属性

### ISSUE THREAD

**Issue by biggeng** [OCSP/OCSP_mainline#100]
在设置输入时，设置输入源应该给每个输入源都配置，因为可能存在不同的输入源来自于不同的kafka集群。

**Comment by DoraemonXX** [comment]
初步看了一下，这样修改对后台的代码改动比较大，因为目前一个datainterface对应一个datasource，而一个task又对应一个datainterface。要么改成一个datainterface对应多个datasource，或者一个task对应多个datainterface。

@raindaywhu 麻烦看一下，有没有好的解决方案，多谢

**Comment by raindaywhu** [comment]
先调研下使用不同的kafka集群，只能创建多个流还是可以在通过一个流包含多个集群的数据。

**Comment by biggeng** [comment]
这个需求的优先级比较低，这个版本不支持。
