### ISSUE TITLE
开启认证之后页面刷新稍有延迟

### ISSUE THREAD

**Issue by DoraemonXX** [OCSP/OCSP_mainline#101]
需要找到具体是哪个阶段导致时间过长，是否可以优惠

**Comment by DoraemonXX** [comment]
目前通过认证缓存机制优化性能

**Comment by biggeng** [comment]
@wangzheng90 , Please append more details of the solution.

**Comment by wangzheng90** [comment]
开启认证之后导致验证延迟时间长的原因有：
1.database与ldap server不在本地，每次认证都需要网络通信，导致认证时间超过1s。
2.当用户名和密码与os用户不匹配时，Linux系统认证需要2-3s才能返回认证失败。因此当开启os用户认证但使用database或ldap用户登录时，每次都需要等待linux系统的认证失败信息，导致认证时间需要2-3s。
解决方法：
在web server本地创建cache缓存文件，每次认证成功时更新cache文件。
认证逻辑为：
1.根据客户端提交的用户token到cache file中进行验证，若cache file中的用户时间戳超时，则认证失败。
2.当cache file认证成功，返回认证信息。
3.当cache file认证失败，到用户配置realm域中进行认证。
4.realm域认证成功则更新cache file。
5.realm域认证失败，返回失败信息。
