### ISSUE TITLE
codis导出程序改造

### ISSUE THREAD

**Issue by biggeng** [OCSP/OCSP_mainline#12]
当前陕西项目，为了提升汇总计算的能力，在导出的过程中计算结果，这样做的一个主要问题是当前的codis导出程序只能在单机上执行。
为了提升程序的扩展性，需要将：1. Codis导出到hdfs. 2. load数据文件到hive表中 3. 使用hive/spark sql计算结果。
其中： 第1项主要考虑使用flume完成。

**Comment by biggeng** [comment]
P2

**Comment by DoraemonXX** [comment]
@biggeng @GalvinYang 
codis数据导出到hdfs基本完成，请查看FlumeAdapter项目

- 目前仍然使用的是keys *的方式获取所有的key

- 一个flume的agent对应一个redis server

下一步考虑使用scan接口实现，对比与keys *的性能

**Comment by DoraemonXX** [comment]
增加redis.algorithm = scan进行配置，如果指定scan那么jedis获取key的方式是通过scan接口，其他情况的实现都是默认使用keys *的方式

下一步需要测试一下两种方式的性能

**Comment by DoraemonXX** [comment]
增加了多线程处理逻辑

**Comment by DoraemonXX** [comment]
redis sink功能完成并测试通过，目前只支持单表对单表，下一步将完成其他需要特殊处理的逻辑。

**Comment by DoraemonXX** [comment]
Please check https://github.com/OCSP/FlumeAdapter
