### ISSUE TITLE
关于多事件融合处理的建议

### ISSUE THREAD

**Issue by haojia3** [OCSP/OCSP_mainline#13]
我们把语音、短信、信令、流量看作是电信的事件，每个事件都有自己的格式，那么有些场景是需要多事件信息融合进行流处理后，才能达到业务需求，例如：需要统计此用户在某个时间段产生了多少流量打了多少个电话。 

所以我们是否可以考虑flume接入多个事件，并统一存储kafka存储到一起，通过一条spark streaming来处理，这样就需要sparkstreaming预处理时，进行多事件的格式适配（这种适配是可配置的），这样就能满足多事件融合处理。 还请酌情考虑下。

**Comment by biggeng** [comment]
P3

**Comment by DoraemonXX** [comment]
@biggeng @haojia3 

例如，3g和4g的问题，信令的格式不同指的是

- 不同个数的字段

- 字段顺序不同

- 不同的字段表示相同的含义

假设3g的信令格式为imsi,lac,cell,age
4g的信令格式为time,imsi,4glac,cell
这两种格式的信令，数量不一致，同样是imsi在不同的位置，lac和4glac是相同的含义但是名字不同，那么做适配之后，就应该是类似这样的一种结果time,imsi,lac,cell,4glac,age相当于两条同一个imsi的信令做一个合集。
这个问题不知道我理解的是否正确？

**Comment by biggeng** [comment]
@DoraemonXX , 信令不同指的是信令的长度和字段均可能不一致。在你的以上例子中：适配后的结果应该为 time, imsi, lac, cell 即取各信令相同的部分（由用户在界面配置取哪些字段）。

**Comment by DoraemonXX** [comment]
修改方案：

1. 在stream_datainterface表中，properties字段的fields属性改为schema，存储的内容格式不变，含义为多种信令的公共字段，并增加fields属性，内容为pname和pvalue。其中pname为用户自定义信令的名字，pvalue为信令的所有字段名字并以逗号分隔，例如：
```json
{
    "props": [
        {
            "pname": "field.numbers", 
            "pvalue": 17
        }, 
        {
            "pname": "topic", 
            "pvalue": "betainput"
        }, 
        {
            "pname": "uniqKeys", 
            "pvalue": "imsi"
        }
    ], 
    "userFields": [ ], 
    "schema": [
        {
            "pname": "imsi", 
            "ptype": "String"
        }, 
        {
            "pname": "bitholding5", 
            "ptype": "String"
        }
    ],
    "fields": [
        {
            "pname": "3g", 
            "ptype": "imsi,lac,cell,bitholding3,bitholding5"
        }, 
        {
            "pname": "4g", 
            "ptype": "imsi,phoneNum,bitholding5"
        }
    ]
}
```

2. 在程序中只能根据信令字段长度，或者信令字段的分隔符进行匹配fields

3. 以上这种方法应该是改动最小的，但是感觉schema和fields配置方式不一致很奇怪，所以还有另一种比较大的表结构的改动，将schema放入到props中，例如：
```json
{
    "props": [
        {
            "pname": "field.numbers", 
            "pvalue": 17
        }, 
        {
            "pname": "topic", 
            "pvalue": "betainput"
        }, 
        {
            "pname": "uniqKeys", 
            "pvalue": "imsi"
        },
        {
            "pname": "schema", 
            "pvalue": "imsi,bitholding5"
        }
    ], 
    "userFields": [ ], 
    "fields": [
        {
            "pname": "3g", 
            "ptype": "imsi,lac,cell,bitholding3,bitholding5"
        }, 
        {
            "pname": "4g", 
            "ptype": "imsi,phoneNum,bitholding5"
        }
    ]
}
```
这种方式对于后台代码的改动比较大，但是json的内容感觉更统一合理一些。

@biggeng @GalvinYang 
大家看看有什么更好的建议，如果当前进度比较紧张，这个feature就不在这个版本中解决

**Comment by biggeng** [comment]
@DoraemonXX schema需要和userFields一起考虑，userFields是用来说明取当前schema的哪一项用来做select 后的项目。支持case when等sql语句。

**Comment by raindaywhu** [comment]
1 经讨论后，基于@DoraemonXX的修改，在stream_datainterface表中，delim字段加入到properties字段中，变为数据源的描述信息之一，properties新增source字段，以描述kafka中存在的多种不同的数据源，每种数据源的描述信息包括 pname 数据源名称， fields 数据源中的字段信息，delim 数据源中的分隔符，userFields 数据源要执行的初始处理。

样例格式如下：
{
    "props": [
        {
            "pname": "field.numbers",
            "pvalue": 17
        },
        {
            "pname": "topic",
            "pvalue": "betainput"
        },
        {
            "pname": "uniqKeys",
            "pvalue": "imsi"
        }
    ],
    "schema": [
        {
            "pname": "imsi",
            "ptype": "String"
        },
        {
            "pname": "bitholding5",
            "ptype": "String"
        }
    ],
    "source": [
        {
            "pname": "3g",
            "fields": "imsi,lac,cell,bitholding3,bitholding5",
	    "userFields": [ ],
	    "delim": "|"
        },
        {
            "pname": "4g",
            "fields": "imsi,phoneNum,bitholding5",
	    "userFields": [ ],
	    "delim": ","
        }
    ]
}

2 处理的流程为：在数据流的transform中，根据不同的数据源执行userFields后，创建多个dataFrame，然后进行合并为一个dataFrame。

**Comment by raindaywhu** [comment]
存储格式更正为：
为减少改动，保留原来的fields 和 userFields格式，只是移动到了sources中


```
{
    "props": [
        {
            "pname": "field.numbers",
            "pvalue": 17
        },
        {
            "pname": "topic",
            "pvalue": "betainput"
        },
        {
            "pname": "uniqKeys",
            "pvalue": "imsi"
        }
    ],
    "schema": [
        {
            "pname": "imsi",
            "ptype": "String"
        },
        {
            "pname": "bitholding5",
            "ptype": "String"
        }
    ],
    "sources": [
        {
            "pname": "3g",
            "delim": "|",
            "fields": [
		        {
		            "pname":"imsi",
		            "ptype":"String"
		        },
		        {
		            "pname":"lac",
		            "ptype":"String"
		        },
		        {
		            "pname":"cell",
		            "ptype":"String"
		        },
		        {
		            "pname":"bitholding3",
		            "ptype":"String"
		        }
            ],
			"userFields": [
			    {
			        "pname":"imsi",
			        "undefined":"on",
			        "pvalue":"(case when eventID in(3, 5, 7) then calledimsi when eventID in(8, 9, 10, 26) then (case when issmsalone=1 then callingimsi when issmsalone=2 then calledimsi else callingimsi end) else callingimsi end)"
			    },
			    {
			        "pname":"imei",
			        "undefined":"on",
			        "pvalue":"(case when eventID in(3, 5, 7) then calledimei when eventID in(8, 9, 10, 26) then (case when issmsalone=1 then callingimei when issmsalone=2 then calledimei else callingimei end) else callingimei end)"
			    },
			    {
			        "pname":"user_phone",
			        "undefined":"on",
			        "pvalue":"(case when eventID in(3, 5, 7) then calledphone when eventID in(8, 9, 10, 26) then (case when issmsalone=1 then callingphone when issmsalone=2 then calledphone else callingphone end) else callingphone end)"
			    }
			]
        }
    ]
}
```

**Comment by raindaywhu** [comment]
[DataInterfaceConf.scala.txt](https://github.com/OCSP/OCSP_mainline/files/668691/DataInterfaceConf.scala.txt)
[DataInterfaceTask.scala.txt](https://github.com/OCSP/OCSP_mainline/files/668694/DataInterfaceTask.scala.txt)
[DataInterfaceServer.scala.txt](https://github.com/OCSP/OCSP_mainline/files/668693/DataInterfaceServer.scala.txt)
[Json4sUtils.scala.txt](https://github.com/OCSP/OCSP_mainline/files/668692/Json4sUtils.scala.txt)

**Comment by DoraemonXX** [comment]
@raindaywhu 
去掉无用的注释，并且去掉rdd.count()之后，看一下性能如何？分析一下性能的形象，多谢

**Comment by raindaywhu** [comment]
在ocbuild01 和 ocbuild02上进行测试
正确性测试：
1 通过log输出每个阶段的数据条目数，数据量级比对无误
2 去掉event中的过滤判断，用kafka-consumer 输出，数据字段内容无误

性能测试：
对比修改前的代码与修改后的代码，单事件数据与两个事件数据，性能差距不大。

[DataInterfaceConf.scala.txt](https://github.com/OCSP/OCSP_mainline/files/676681/DataInterfaceConf.scala.txt)
[DataInterfaceServer.scala.txt](https://github.com/OCSP/OCSP_mainline/files/676682/DataInterfaceServer.scala.txt)
[DataInterfaceTask.scala.txt](https://github.com/OCSP/OCSP_mainline/files/676679/DataInterfaceTask.scala.txt)
[Json4sUtils.scala.txt](https://github.com/OCSP/OCSP_mainline/files/676680/Json4sUtils.scala.txt)

**Comment by raindaywhu** [comment]
测试环境性能比对结果
修改后 
![image](https://cloud.githubusercontent.com/assets/11971136/22060915/bd756b84-ddad-11e6-9a6b-43efcf1bccb4.png)

修改前
![image](https://cloud.githubusercontent.com/assets/11971136/22060945/d29571da-ddad-11e6-9b25-6568be7ce16d.png)

**Comment by YangJie9** [comment]
可以把这个issue#60挂到这个下边，只要取有效字段去处理就行
