### ISSUE TITLE
参数配置优化

### ISSUE THREAD

**Issue by DoraemonXX** [OCSP/OCSP_mainline#146]
对于事件的参数，如果前台开放配置的，按照用户的修改更新，如果前台没有配置的，后台更新之后，前台不应该覆盖隐藏参数。目前覆盖隐藏参数的方式影响特殊需求的本地开发。

**Comment by twicoder** [comment]
Merge STREAM_EVENT.PROPERTEIS column data, first merge the most outer properties, then merge PROPERTIES.props data
