### ISSUE TITLE
优化spark sql程序

### ISSUE THREAD

**Issue by biggeng** [OCSP/OCSP_mainline#15]
当前的spark sql程序是使用spark context方式去查询，可以考虑通过连接thrift server的方式查询。

**Comment by DoraemonXX** [comment]
目前有3种方式可以使用
![sql](https://cloud.githubusercontent.com/assets/21124194/20329487/7cc5a830-abd3-11e6-8e97-b5727d743f47.png)

需要测试和调研一下性能和可扩展性

**Comment by DoraemonXX** [comment]
Please check https://github.com/OCSP/sparksqlCmd
