### ISSUE TITLE
[Kerberos]增加kerberos启用开关，并配置相关属性

### ISSUE THREAD

**Issue by DoraemonXX** [OCSP/OCSP_mainline#153]
在UI上可以通过开关设置是否启用kerberos认证模式，如果启用需要用户填写Realm和Keytab的文件路径，提交spark任务的时候，根据当前登陆用户以及Realm生成principal。保证在后台启动spark任务的用户就是当前登陆用户。

**Comment by raindaywhu** [comment]
在mainFrame中增加：KERBEROS_ENABLE，目前测试阶段设置为true
`@@ -21,6 +21,7 @@ object MainFrameConf {

   val MONITOR_TASK_MONITOR_ENABLE = "ocsp.monitor.task-monitor.enable"
   val EXTRAID = "ocsp.event.append-id.enable"
+  val KERBEROS_ENABLE = "ocsp.kerberos.enable"

   initMainFrameConf()

@@ -40,6 +41,7 @@ object MainFrameConf {
     sysdata.foreach(x => {
       systemProps.set(x.get("name").get, x.get("value").get)
     })
+    systemProps.set(KERBEROS_ENABLE, "true")
   }`

**Comment by DoraemonXX** [comment]
Please check https://github.com/OCSP/OCSP_mainline/wiki/OCSP-Security
