### ISSUE TITLE
11月17日上午ui沟通会议内容

### ISSUE THREAD

**Issue by haojia3** [OCSP/OCSP_mainline#16]
待完善和调整的内容：
1、第一次登陆，快速导航就能完成一个作业的配置
2、标签管理，id不用显示
3、标签上传时，判断库中已有的name替换并保留properties信息，如果库中没有则新增加，如果jar包中没有则删掉或者表状态，如果有在跑的job，则不允许上传
4、删掉add、delete。name写死，description去掉。浮框显示信息；
5、datasource中，type 改成选择方式，只有两个kafka和codes
6、datasource中，properties内容拆分成单项。
7、新建任务-基础配置，只留task name，其他不要
8、增加分步检查；
9、删除input datasource，topic提上面并改成kafka topic
10、设置标签，只保留name，不要classname，增加直观的排序
11、设置输出中，不出现properties
12、设置事件中，不出现properties
13、tasks中，增加是否运行的状态

远期内容：
多个标签jar包上传支持
输入框的非法检查
topic是否可以直接从kafka中读取

**Comment by DoraemonXX** [comment]
@lishan 这次会议我没有参加，不清楚具体的内容，但是还请根据会议结论看一下哪些需要加入到2.0版本中，多谢

@biggeng @GalvinYang
