### ISSUE TITLE
设置输入的问题

### ISSUE THREAD

**Issue by DoraemonXX** [OCSP/OCSP_mainline#189]
1. 转义字段名和值后台要保持和原有的一致，pname和pvalue

2. 可用字段不应该在关联出转义字段名

**Comment by twicoder** [comment]
需要确认需求2）

**Comment by DoraemonXX** [comment]
下面这种情况

![snip20170816_19](https://user-images.githubusercontent.com/21124194/29340943-3c6c9282-8254-11e7-9dcb-2c68b3ebc9fb.png)
