### ISSUE TITLE
需要添加空指针保护

### ISSUE THREAD

**Issue by DoraemonXX** [OCSP/OCSP_mainline#19]
@biggeng @GalvinYang 

和OCSP_WEB联调到过程中，发现如果用户不输入的字段，OCSP获取的时候会有空指针的情况，例如filter_expr字段。之前初始化的时候给的是空字符串所有没有问题，但是现在新建如果不填，存入数据库的值是null。

**Comment by DoraemonXX** [comment]
@raindaywhu
Please handle it, thanks

**Comment by raindaywhu** [comment]
为filter_expr、delim添加默认值
driver运行时，检查需要用到的配置，添加了uniqKeys 和 topic的检查

[DataInterfaceServer.scala.diff.txt](https://github.com/OCSP/OCSP_mainline/files/642150/DataInterfaceServer.scala.diff.txt)
[BaseConf.scala.diff.txt](https://github.com/OCSP/OCSP_mainline/files/642151/BaseConf.scala.diff.txt)
[DataInterfaceTask.scala.diff.txt](https://github.com/OCSP/OCSP_mainline/files/642153/DataInterfaceTask.scala.diff.txt)

**Comment by DoraemonXX** [comment]
@raindaywhu 
According to our discussion, please go ahead, thanks.

**Comment by raindaywhu** [comment]
@DoraemonXX 
调整后的diff如下：
[DataInterfaceTask.scala.diff.txt](https://github.com/OCSP/OCSP_mainline/files/648502/DataInterfaceTask.scala.diff.txt)
[BaseConf.scala.diff.txt](https://github.com/OCSP/OCSP_mainline/files/648503/BaseConf.scala.diff.txt)
[DataInterfaceServer.scala.diff.txt](https://github.com/OCSP/OCSP_mainline/files/648504/DataInterfaceServer.scala.diff.txt)
