### ISSUE TITLE
解决executor连接数据库的问题

### ISSUE THREAD

**Issue by biggeng** [OCSP/OCSP_mainline#2]
当前的代码架构中，除了driver会连接数据库外，exectuor也会连接数据库获得相应的系统配置，这样的主要问题是会造成数据库连接过多的exception。
需要改造为：由driver统一连接数据库，然后由driver将相应的配置分发到executor中。

**Comment by DoraemonXX** [comment]
@biggeng @GalvinYang 

可以将driver中从数据库得到的配置数据，通过广播变量的方式使每个计算节点只有一个副本，所有这个节点上的executor共用这个变量。

具体方案就是将DataInterfaceTask中的成员变量conf，labels ，events进行广播，代码中不再使用这些成员变量，而在process方法中改用局部变量进行传递，例如：
    val broad_conf = ssc.sparkContext.broadcast(conf)
    val broad_labels = ssc.sparkContext.broadcast(labels)
    val broad_events = ssc.sparkContext.broadcast(events)
具体方案可以再详细讨论。

**Comment by biggeng** [comment]
P2

**Comment by biggeng** [comment]
@DoraemonXX @GalvinYang 请帮忙review下以上的代码。谢谢！

**Comment by biggeng** [comment]
修改了连接jodis部分的代码，改为在进程层连接。因为jodis client的bug, 每次close的时候会因此zookeeper的关闭race condition问题，会触发以下问题
16/12/07 00:01:55 ERROR imps.CuratorFrameworkImpl: Background exception was not retry-able or retry gave up
java.lang.IllegalStateException: instance must be started before calling this method
        at org.spark-project.guava.base.Preconditions.checkState(Preconditions.java:149)
        at

**Comment by biggeng** [comment]
Close this issue since it has been done.
