### ISSUE TITLE
启动脚本运行失败

### ISSUE THREAD

**Issue by DoraemonXX** [OCSP/OCSP_mainline#20]
目前，启动命令中已经不需要指定--files common.xml和log4j.properties
需要修改stream_start.sh和MainFrameManager相关代码。

**Comment by raindaywhu** [comment]
删除MainFrameManager mkcmd中 files相关参数
删除init.sql中 files相关初始化参数
调整 stream_start.sh 脚本

测试：
目前只进行了MainFrame的启动测试。

taks 的启动停止 尚未进行

**Comment by DoraemonXX** [comment]
@raindaywhu @biggeng 
Please remove `$FWDIR/conf/common.xml:$FWDIR/conf/log4j.properties` in stream_start.sh and only submit stream_start.sh and MainFrameManager.scala changes. Thanks, go ahead.

**Comment by raindaywhu** [comment]
Done

[MainFrameManager.scala.diff.txt](https://github.com/OCSP/OCSP_mainline/files/630299/MainFrameManager.scala.diff.txt)
[stream_start.sh.diff.txt](https://github.com/OCSP/OCSP_mainline/files/630298/stream_start.sh.diff.txt)
