### ISSUE TITLE
支持没有label的业务

### ISSUE THREAD

**Issue by biggeng** [OCSP/OCSP_mainline#22]
OCSP的基本流程是先打标签，然后再做事件处理。如果没有打标签的工作，实质上还是要进入到execLabel的函数中进行一些处理。
这样做可能对性能有一定的损耗，需要在进入前进行判断，如果没有标签，直接进入到事件处理的步骤。

**Comment by rainflower** [comment]
这个这次在沈阳也有提到，如果没有lable能否直接输出的问题。

**Comment by YangJie9** [comment]
@DoraemonXX  进过测试，如果不改代码，需要9s，改动后大概需要6s ，diff文件如下：
diff --git a/core/src/main/scala/com/asiainfo/ocdp/stream/datasource/DataInterfaceTask.scala b/core/src/main/scala/com/asiainfo/ocdp/stream/datasource/DataInterfaceTask.scala
index 1208161..fc1ecee 100755
--- a/core/src/main/scala/com/asiainfo/ocdp/stream/datasource/DataInterfaceTask.scala
+++ b/core/src/main/scala/com/asiainfo/ocdp/stream/datasource/DataInterfaceTask.scala
@@ -86,6 +86,7 @@ class DataInterfaceTask(id: String, interval: Int) extends StreamTask {
         else dataFrame.selectExpr(allItemsSchema.fieldNames: _*)
 
       //  if (mixDF.count > 0) {
+        if (labels.size > 0) {
           val t3 = System.currentTimeMillis
           println("3.DataFrame 最初过滤不规则数据耗时 (millis):" + (t3 - t2))
           val labelRDD = execLabels(mixDF)
@@ -105,6 +106,23 @@ class DataInterfaceTask(id: String, interval: Int) extends StreamTask {
 
           println("6.所有业务营销 耗时(millis):" + (System.currentTimeMillis - t5))
         }
+        else{
+
+          val t3 = System.currentTimeMillis
+          println("3.DataFrame 最初过滤不规则数据耗时 (millis):" + (t3 - t2))
+
+          mixDF.persist()
+          mixDF.count()
+          val t4 = System.currentTimeMillis
+          println("4.mixDF count耗时(millis):" + (t4 - t3))
+
+          makeEvents(mixDF, conf.get("uniqKeys"))
+          mixDF.unpersist()
+          println("6.所有业务营销 耗时(millis):" + (System.currentTimeMillis - t4))
+
+        }
+
+        }
 
         else{
           println("当前时间片内正确输入格式的流数据为空, 不做任何处理.")

**Comment by YangJie9** [comment]
@DoraemonXX 进过测试，如果不改代码，需要9s，改动后大概需要6s ，diff文件如下：
[a.txt](https://github.com/OCSP/OCSP_mainline/files/629990/a.txt)

**Comment by DoraemonXX** [comment]
@YangJie9 , thanks OK for me, please go ahead

**Comment by biggeng** [comment]
The diff is Ok to me. Please go ahead.

**Comment by DoraemonXX** [comment]
Fixed. Please check [Commits log](https://github.com/OCSP/OCSP_mainline/commit/c922f6e32d67d378c0ba62379522ee7c6c48755c)
