### ISSUE TITLE
降低event job处理时的task数（即rdd partition数）

### ISSUE THREAD

**Issue by biggeng** [OCSP/OCSP_mainline#23]
当前spark 作业的task数是由kafka partition数决定的，这导致了一个问题：当需要处理的数据量比较大时，往往通过增大kafka partition数提升效率。但是在event输出处理时，由于有一定的filter，所以filter之后的数据量不大，如果task过多，会造成额外的消耗。
因此，建议在执行完label打标签后，在event job提交之前进行partition合并，降低partition数。

**Comment by DoraemonXX** [comment]
合并partition有两个方法，repartition和coalesce，通过源码看这两个方法的实现
```scala
  def repartition(numPartitions: Int)(implicit ord: Ordering[T] = null): RDD[T] = withScope {
    coalesce(numPartitions, shuffle = true)
  }
```
其实repartition调用的就是coalesce，只是coalesce默认第二个参数是false。
下面是coalesce方法的官方注释，可以看到如果是“drastic coalesce”那么还是建议设置shuffle = true，
从实际考虑目前不会产生巨大的partition的变化，先用coalesce实现合并partition的功能。

   >Return a new RDD that is reduced into `numPartitions` partitions.
   >
   >This results in a narrow dependency, e.g. if you go from 1000 partitions
   >to 100 partitions, there will not be a shuffle, instead each of the 100
   >new partitions will claim 10 of the current partitions.
   >
   >However, if you're doing a drastic coalesce, e.g. to numPartitions = 1,
   >this may result in your computation taking place on fewer nodes than
   >you like (e.g. one node in the case of numPartitions = 1). To avoid this,
   >you can pass shuffle = true. This will add a shuffle step, but means the
   >current upstream partitions will be executed in parallel (per whatever
   >the current partitioning is).
   >
   >Note: With shuffle = true, you can actually coalesce to a larger number
   >of partitions. This is useful if you have a small number of partitions,
   >say 100, potentially with a few partitions being abnormally large. Calling
   >coalesce(1000, shuffle = true) will result in 1000 partitions with the
   >data distributed using a hash partitioner.

**Comment by DoraemonXX** [comment]
@biggeng @GalvinYang 

- 修改方案
 以codis输出为例，根据需求df过滤之后会将结果写入codis，每个partition都会建立一个连接。那么在StreamCodisWriter中的transforEvent2CodisMessage调用之后调用coalesce合并partition，这样下面RDD调用mapPartitions的时候就是合并之后的结果了

- 测试用例
  coalesce需要指定一个新的partition的个数，暂时的策略是个数减半。通过spark的history的页面可以看到，在输出到codis的时候，partition的数量确实已经减半。
 

 ***修改前***
       可以看到原始的partition是4个所以一直在一个stages里启动的就是4个task
     
![snip20161130_3](https://cloud.githubusercontent.com/assets/21124194/20746706/da30125e-b721-11e6-8e98-d6c55a049cb9.png)

***修改后***
可以看到在输出的时候partition已经减半

![snip20161130_2](https://cloud.githubusercontent.com/assets/21124194/20746981/378a6dae-b723-11e6-8096-b7f1ae26c4cf.png)

**Comment by biggeng** [comment]
Hi @DoraemonXX . Please go ahead and paste the diff. Thanks!

**Comment by DoraemonXX** [comment]
@biggeng @GalvinYang 
Please review the changes, thanks.

在stream_datainterface表中加入一个新的字段numPartitions，

- 作为输入的interface的时候，可以用来repartition，不再根据kafka的partition进行计算

- 作为输出的interface的时候，用来进行partition的合并

注意：如果使用最新的代码，请在数据库中运行下面的语句添加一个新的属性
`alter table stream_datainterface add column numPartitions int(9);`

**Comment by biggeng** [comment]
@DoraemonXX 不建议在数据库中增加numPartitions这个字段，这样会过多的骚扰用户，用户需要学习太多的配置参数。
建议：1. 给定一个我们认为可以提升性能的缩小partition比例，如10倍或100倍。直接按照我们的默认比例进行减少partition，不需要让用户知道这个参数的存在。

**Comment by DoraemonXX** [comment]
根据@biggeng的建议，已经将数据库还原，不需要对数据库有任何的修改，默认比例缩小10倍。
如果缩小之后导致程序有任何的问题，可以在stream_event中为event的PROPERTIES属性配置numPartitions参数，例如：
`"props":[{"pname":"userKeyIdx","pvalue":2},{"pname":"numPartitions","pvalue":66}]`
