### ISSUE TITLE
spark的partition数和kafka的partition数解耦

### ISSUE THREAD

**Issue by DoraemonXX** [OCSP/OCSP_mainline#25]
目前spark中的partition的数量是由kafka的partition决定的，可以使用目前在stream_datainterface表中的numPartitions配置进行repartition，默认不配置这个参数或者值小于1，表示不进行repartition。

**Comment by DoraemonXX** [comment]
@biggeng @GalvinYang 

进行了一下测试，原始kafka的partition为1000，流入到spark streaming之后进行repartition变成100，最终event输出到时候partition缩小为10，运行时间如下：
![snip20161201_1](https://cloud.githubusercontent.com/assets/21124194/20788673/b4cd2076-b7ec-11e6-920b-6f919f8dc4ee.png)

**Comment by biggeng** [comment]
@DoraemonXX 看来repartition是一个很耗时的操作，如果这样的话，建议不要做repartition.

**Comment by biggeng** [comment]
Close the issue.
