### ISSUE TITLE
打标签异常处理

### ISSUE THREAD

**Issue by biggeng** [OCSP/OCSP_mainline#28]
由于标签函数是由定制开发团队开发，因此可能出现一些异常问题，例如null point exception等异常，这时候如果在core部分不进行catch，会导致spark task failed并且retry，会造成整体性能差。
建议：在core部分execLabels函数中执行打标签部分进行try catch优化，处理由attachLabels里抛出的异常。

**Comment by DoraemonXX** [comment]
@raindaywhu 
Please handle it, thanks

**Comment by raindaywhu** [comment]
计划进行如下的修复：
1 在excutor 捕获异常信息，传递给driver，由driver 输出异常到日志中，以方便分析stream的运行信息。
2 数据集的预测试  通过读取特定目录或者数据库中的样例数据，先进行接口函数测试。 

首先完成1的工作。

**Comment by biggeng** [comment]
@raindaywhu Thanks!
我建议只需要在executor中catch exception，不需要向driver传递log信息。

**Comment by raindaywhu** [comment]
先在executor中catch异常信息，修复该问题

进行的测试：
创建测试用DataInterface，在相关接口中直接抛出异常，运行fix后的core， 可以看到driver会在执行event期间找不到数据的lable而异常退出

[DataInterfaceTask.scala.diff.txt](https://github.com/OCSP/OCSP_mainline/files/648497/DataInterfaceTask.scala.diff.txt)

@biggeng  请帮忙review

**Comment by DoraemonXX** [comment]
@raindaywhu 
Thanks, OK for me, please go ahead

**Comment by raindaywhu** [comment]
Done
