### ISSUE TITLE
OCSP程序安装包

### ISSUE THREAD

**Issue by biggeng** [OCSP/OCSP_mainline#3]
OCSP后台程序与web 需要部署在同一台机器中，因此需要将这两部分程序打到一个安装包，以简化用户安装部署工作。

**Comment by biggeng** [comment]
P1

**Comment by DoraemonXX** [comment]
请@raindaywhu 和@lishan沟通一下，基于目前OCSP的打包方式，看看怎么更好的和web结合在一起，多谢

**Comment by raindaywhu** [comment]
修改 build.sh 将web 和 OCSP的包打在一起
web是免编译，去除pom文件中的web
最终产品使用的是prod, 修改web/server/config.js 默认为prod

[config.js.diff.txt](https://github.com/OCSP/OCSP_mainline/files/651186/config.js.diff.txt)
[pom.xml.diff.txt](https://github.com/OCSP/OCSP_mainline/files/651188/pom.xml.diff.txt)
[build.sh.diff.txt](https://github.com/OCSP/OCSP_mainline/files/651187/build.sh.diff.txt)

**Comment by biggeng** [comment]
需要将程序包打包为rpm。
谢谢！

**Comment by raindaywhu** [comment]
执行最新build.sh 脚本，会将web目录一起打包
将打好的tar包放入到 rpmbuild/SOURCES中
OCSP.spec 文件放入到SPECS
然后执行 rpmbuild -bb OCSP.spec

[OCSP.spec.txt](https://github.com/OCSP/OCSP_mainline/files/654359/OCSP.spec.txt)

@biggeng  请review 相关展示信息， 包括安装过程中的提示信息

**Comment by biggeng** [comment]
Thanks @raindaywhu . Good Job!
The diff is OK to me. Please go ahead.

**Comment by raindaywhu** [comment]
done
