### ISSUE TITLE
event cache和label cache问题

### ISSUE THREAD

**Issue by biggeng** [OCSP/OCSP_mainline#30]
现在codis里的label cache和event cache的prefix都是写死的，如果同时上多个业务，会造成多个业务同时写到label里的问题。
需要每个业务有自己的label cache 和event cache.

**Comment by DoraemonXX** [comment]
此问题将会做如下修改：
- 最终在codis里面生成的cache的名字分别为eventCache_task1:4600092691019401和labelCache_task1:4600092691019401，其中task1为任务的名字

- 由于executor中要获取task的名字，所以要将TaskConf的对象广播到所有节点

- 所以DataInterfaceTask的构造函数的参数将改为TaskConf类型，这样在driver里就可以得到TaskConf的对象

**Comment by DoraemonXX** [comment]
@biggeng @GalvinYang

Please review the changes, thanks.

**Comment by DoraemonXX** [comment]
Fixed
