### ISSUE TITLE
计算当前作业的已经执行时间

### ISSUE THREAD

**Issue by biggeng** [OCSP/OCSP_mainline#38]
在页面需要展示作业的持续运行时间。

**Comment by DoraemonXX** [comment]
在STREAM_TASK中添加start_time，当任务状态变成2的时候插入时间戳，当任务状态变成0的时候将这个字段变成空，请@lishan处理前台的逻辑，多谢

**Comment by biggeng** [comment]
Close this issue, since it has been done.
