### ISSUE TITLE
数据接入统计

### ISSUE THREAD

**Issue by biggeng** [OCSP/OCSP_mainline#4]
当前的spark streaming从Kafka读入数据时，如果数据格式不符合预设的schema，则将这条数据丢弃。但是并没有将丢弃的数据统计。为了提高系统的用户友好型，需要考虑是否统计合规的数据比例。

**Comment by DoraemonXX** [comment]
@biggeng @GalvinYang 

这个问题参考spark官方的样例RecoverableNetworkWordCount，可以使用累加器的功能解决。
尝试修改了一下代码，在DataInterfaceTask的transform方法中进行累加。但是累加器有个问题每次调用rdd的action转换的时候会重复计算，要用persist方法解除依赖直接的关系。
所以将mixDF.count改为mixDF.persist().count就可以解决重复的问题。具体方案可以再详细讨论。

**Comment by biggeng** [comment]
暂时不加进到OCSP2.0的scope里。

**Comment by biggeng** [comment]
这个问题可以结合其他的debug ability需求一起看，例如：需要打印当前信令所在partition信息等。
有一个初步的思路：这些debug数据在log里不是很好展示，可以通过增加一个debug event, 考虑将这些debug信息输出到Kafka中。 @DoraemonXX

**Comment by DoraemonXX** [comment]
基于spark2.1的代码使用累加器实现该功能，将结果暂时写入driver的日志文件中
测试用例：

1. 向kafka输入条记录
```
20170302141742885|20170302141842885|13910362058|4600092691019402|2|31251|5125|31251|5125||0|111|13710642049|1019401|00000000000|1|91
20170302141742885|20170302141842885|13910362058|4600092691019402|2|31251|5125|31251|5125||0|111|13710642049|1019401|00000000000|1
20170302141742885|20170302141842885|13910362058|4600092691019402|2|31251|5125|31251|5125||0|111|13710642049|1019401|00000000000|1|
```

3.Streaming运行情况为 
![snip20170302_1](https://cloud.githubusercontent.com/assets/21124194/23495773/874f7ada-ff55-11e6-88d5-1c1332c86d63.png)


3. 在MainFrameManager.log中可以得到如下结果
```
2017-03-02 14:30:30,189 INFO [streaming-job-executor-0] DataInterfaceTask:36 - Dropped 1 records since their schema size is 17 not matching records field size.
2017-03-02 14:30:30,189 INFO [streaming-job-executor-0] DataInterfaceTask:36 - Reserved 2 records successfully.
```

注：暂时将结果存储在日志中，后续可以优化存储方案
@biggeng

**Comment by DoraemonXX** [comment]
基于spark1.6的代码也已经完成，测试效果同上。、
1.6和2.1的区别是累加器的类型，1.6使用的是`Accumulator[Long]`而2.1使用的是`LongAccumulator`

**Comment by DoraemonXX** [comment]
ocsp.monitor.records-correctness.enable表示是否开启统计功能
每隔ocsp.monitor.records-correctness.retain-check-interval-mins（默认2880分钟，即2天）分钟检查一次统计结果是否保存时间超过了ocsp.monitor.records-correctness.retain-mins（默认10080分钟，即7天）分钟，如果超过了会直接删除

**Comment by DoraemonXX** [comment]
Done
