### ISSUE TITLE
保存之后能否可选不立即执行

### ISSUE THREAD

**Issue by jesusRUi** [OCSP/OCSP_mainline#49]
配置完一个工作流之后，点击保存，就自动启动了。但是对于有些需求来说，我们只是配置一个工作流，当成一个参考模版。建议在最后添加一个控制按钮，“保存运行”，“保存不运行”。

**Comment by DoraemonXX** [comment]
Please handle this issue, thanks

**Comment by lishan** [comment]
Fixed, task will be stopped when new created.
