### ISSUE TITLE
添加输入输出字段配置表

### ISSUE THREAD

**Issue by jesusRUi** [OCSP/OCSP_mainline#50]
像山东这边有的需要配置100多个字段，能否添加字段配置表，我们在使用的时候配置这个配置表，在创建工作流的输入源和输出源字段的时候，就可以直接选择这些字段名，而不会一个一个的敲，如果需要增加一个新的输出事件的时候也会可以复用这些字段。

**Comment by DoraemonXX** [comment]
@jesusRUi 
目前我们这些字段是可以复制粘贴出来的，ctrl + a 全选，然后复制，粘贴出来是以逗号分隔各个字段的，可以修改添加，在复制回去，所以理论上只需要一个一个敲一次。不知道这样是否满足你说的**复用**？

**Comment by biggeng** [comment]
Close this issue, user can copy  schema using ctrl + command.
