### ISSUE TITLE
标签配置jar无法上传

### ISSUE THREAD

**Issue by jesusRUi** [OCSP/OCSP_mainline#53]
现场环境，往服务器传文件是有4A限制的，在我们本地上传时，报错：premission denied。这就根本无法打标签了。

**Comment by biggeng** [comment]
这个问题是因为在某些场景下，因为网络策略，无法从桌面机通过浏览器上传。需要改进的是：
1. 增加一个手动上传包的方法，由用户自己上传标签包到指定目录
2. 增加一个检测标签包的命令，在用户上传包之后，运行该命令，可以完成检测标签并且插入到数据库中。

**Comment by lishan** [comment]
当上传失败的时候，前端提示上传jar包的位置

**Comment by raindaywhu** [comment]
stream命令增加子命令 admin -loadlabel <jarfile>来加载jar包中的类到数据库中。


[stream.diff.txt](https://github.com/OCSP/OCSP_mainline/files/689374/stream.diff.txt)

[Admin.scala.txt](https://github.com/OCSP/OCSP_mainline/files/689376/Admin.scala.txt)

**Comment by DoraemonXX** [comment]
几点小建议

- 包的名字com.asiainfo.ocdp.stream.client.cli用这个比较好一点，类的名字用AdminCLI

- 帮助里面jarname改成label jar path

- 成功之后最好写上"load label " + labelName + " successfully"

- 输入sh bin/stream admin的时候应该提示的错误是Unknown option而不应该是Wrong jarfile name

- 输入sh bin/stream admin -loadlabel时候错误应该是无效路径，因为相当于输入了一个空的路径

- 输入sh bin/stream admin -loadlabel ab的时候，不应该抛异常，应该提示无效路径，因为ab这个路径根本不存在

- 帮助信息是不是类似这样更美观一点
```
Usage: yarn rmadmin
   -refreshQueues 
   -refreshNodes 
   -refreshNodesResources 
   -refreshSuperUserGroupsConfiguration 
   -refreshUserToGroupsMappings 
   -refreshAdminAcls 
   -refreshServiceAcl 
   -getGroups [username]
```

**Comment by raindaywhu** [comment]
@biggeng  fixed

[stream.diff.txt](https://github.com/OCSP/OCSP_mainline/files/689561/stream.diff.txt)

[AdminCLI.scala.txt](https://github.com/OCSP/OCSP_mainline/files/689560/AdminCLI.scala.txt)

**Comment by DoraemonXX** [comment]
Good，代码中的label单词注意统一一下，测试没有问题就可以提交了

Tip：有时间可以考虑一下代码的扩展性，如果要新加一个操作，那么main函数里面是不是`val str = options.get('jarfile).getOrElse("")`以下的内容都需要改动，有没有什么更好的写法可以只增加新的方法而原有的代码改动量最少呢。对于-loadlabel后面参数的校验，统一在一个地方处理是不是会更清晰一些。个人建议，仅供参考啊:)
