### ISSUE TITLE
cannot resolve '' given input columns

### ISSUE THREAD

**Issue by lidongrabbit** [OCSP/OCSP_mainline#55]
1. spark.sql.AnalysisException:cannot resolve 'sca_app_id' given input columns
  测试时发现打标签时streaming里面没有数据时报这个错误

**Comment by biggeng** [comment]
@lidongrabbit 能不能具体的说下场景

**Comment by lidongrabbit** [comment]
如果某个批次的数据量为0，启动ocsp就会报上面的错误启动失败，运行过程中也会因这个错误退出程序。杨姐这个问题已经解决了，修改了山东这边的代码
