### ISSUE TITLE
程序能否增加直接读取HDFS数据

### ISSUE THREAD

**Issue by jesusRUi** [OCSP/OCSP_mainline#56]
目前这边有个需求，文件已经落地到HDFS，我们的流处理平台能否直接读取hdfs作为输入源？

**Comment by jesusRUi** [comment]
看原先的代码，是有这个功能的，但是被注释掉了。

**Comment by biggeng** [comment]
从HDFS读取数据 可能会因为HDFS的不稳定性造成Spark streaming读取数据不稳定，建议使用nifi或者flume读取hdfs数据，再输出到kafka中，spark streaming只从Kafka中处理流数据。
