### ISSUE TITLE
增加告警和failover机制

### ISSUE THREAD

**Issue by biggeng** [OCSP/OCSP_mainline#58]
当程序进程因为异常退出时，有告警给用户，并且提供failover机制，将失败的作业重新运行。

**Comment by raindaywhu** [comment]
将告警功能与failover机制拆分为两个issuse。本issuse处理failover机制。
预计提供两种级别的failover，用户在不同场景下可以选择：
1 性能优先模式。 失败后，忽略上次失败的数据，直接从最新的数据开始重新处理。
2 数据优先模式。 失败后，从上次的出错的数据开始处理。
    需要评估checkpoint的开销和recover 时间。
    在checkpoint失效或者开销过大的情况下通过保存kafka的消费offset来重新启动任务。
    优先实现exactly-once语义，如果实现复杂，实现at-most-once语义。

**Comment by raindaywhu** [comment]
1 checkpoint 有缺陷，当代码发生变化时，不能从老的checkpoint中进行恢复。
2 exactly-once 语义 实现需要修改output实现，与offset一起存储。实现稍微麻烦。
3 根据需求，首先实现记录offset来进行恢复的 at-most-once 语义的版本。

**Comment by raindaywhu** [comment]
通过Kafka提供的KafkaCluster类来提交offset到ZOOKEEPER中。
启动时首先尝试读取offset。

[DataInterfaceTask.scala.txt](https://github.com/OCSP/OCSP_mainline/files/779674/DataInterfaceTask.scala.txt)
[DataSourceConstant.scala.txt](https://github.com/OCSP/OCSP_mainline/files/779675/DataSourceConstant.scala.txt)

[KafkaCluster.scala.txt](https://github.com/OCSP/OCSP_mainline/files/779682/KafkaCluster.scala.txt)
[KafkaReader.scala.txt](https://github.com/OCSP/OCSP_mainline/files/779684/KafkaReader.scala.txt)
[StreamingSource.scala.txt](https://github.com/OCSP/OCSP_mainline/files/779683/StreamingSource.scala.txt)
[StreamingSourceFactory.scala.txt](https://github.com/OCSP/OCSP_mainline/files/779685/StreamingSourceFactory.scala.txt)

**Comment by raindaywhu** [comment]
增加重试机制，数据库STREAM_TASK表中增加字段设置重试次数
[TaskConf.scala.txt](https://github.com/OCSP/OCSP_mainline/files/789888/TaskConf.scala.txt)
[TaskConstant.scala.txt](https://github.com/OCSP/OCSP_mainline/files/789889/TaskConstant.scala.txt)

[StreamingInputReader.scala.txt](https://github.com/OCSP/OCSP_mainline/files/789892/StreamingInputReader.scala.txt)
[StreamApp.scala.txt](https://github.com/OCSP/OCSP_mainline/files/789890/StreamApp.scala.txt)
[TaskServer.scala.txt](https://github.com/OCSP/OCSP_mainline/files/789891/TaskServer.scala.txt)

[example_init.sql.txt](https://github.com/OCSP/OCSP_mainline/files/789900/example_init.sql.txt)

**Comment by raindaywhu** [comment]
重试不能在同一个JVM中进行，可能会导致SparkContext清理的问题。
需要新的重试策略：在MainFrame中进行RETRY状态判断和重试。MainFrame和 StreamApp 通过数据库进行通讯。当stream出现异常时，StreamApp自行标记为异常。 在MainFrame中根据task的异常状态进行重试策略。

**Comment by raindaywhu** [comment]
目前 关闭了启动读取offset 功能，以避免读取的offset与当前偏移差距过大的情况下，会导致数据不能及时处理，当遇到这种case时再开启。
