### ISSUE TITLE
产品方面的建议，后续不断补充！

### ISSUE THREAD

**Issue by haojia3** [OCSP/OCSP_mainline#7]
1.对于目前过滤掉的记录、字段内容，是否考虑按照错单阶段性记录下。因为在详单、流量等跟钱有关系的场景中，局方或者第三方可能会提出时间段内稽核的诉求。
2.对于产品来说，建议有简单的系统管理，比如简单的用户，简单的日志等。
3.对于订阅规则可以考虑简单的生命周期，例如生失效的时间，目前规则较少倒是没啥必要。

以上是个人的一些理解，有不对的还请予以纠正，谢谢！

**Comment by biggeng** [comment]
2. P2
3. OCSP2.0不进

**Comment by YangJie9** [comment]
关于第一个需求，经过郝佳的确认，就是认为非法数据需要保留副本。我觉的可以加到FlumeAdapter的flume-socket-source里边，判断出错单数据可以就地周期性的写文件到本地，以做备份。

**Comment by biggeng** [comment]
close this issue, it has been fixed.
