### ISSUE TITLE
UI界面上未处于运行状态的stream点击重启后卡死

### ISSUE THREAD

**Issue by raindaywhu** [OCSP/OCSP_mainline#70]
当在UI界面上操作一个stream时，如果这个stream还未运行过，执行重启后，该stream的状态一直处于正在重启中，并且后台并不会执行重启，会一直无法操作。

**Comment by raindaywhu** [comment]
该问题需要进行如下处理：
1  stream的状态不是未执行时，不能进行重启操作
2 后台逻辑应当处理prerestart的状态， 以程序加强健壮性。需要check 当前定义的状态，是否还有遗漏。

**Comment by lishan** [comment]
前端界面修改，
1. web界面上不显示restart按钮当task是stop状态下。
2. RestAPI允许进行修改当stop状态下重启任务。

**Comment by DoraemonXX** [comment]
Fixed
