### ISSUE TITLE
2017.2月Web需求（多租户，数据订阅，重试次数，告警）

### ISSUE THREAD

**Issue by lishan** [OCSP/OCSP_mainline#72]
1. 重试次数。

a. 前台界面显示配置项，重试次数（数字格式），可以在修改配置项中修改重试次数
b. 显示“重试”的task状态。
c. 后端数据库初始化脚本修改。 @raindaywhu 

评估：1.5Day(难点:校验输入是整数类型)

2. 多租户需求

a. 和OCDP的LDAP集成，需要考虑登录的时候调用LDAP访问的API
b. Admin用户存在OCSP的数据库中
c. Admin和普通用户之间都有特定访问控制（为了简单起见，权限是固定的）

评估：3.5Day(难点: LDAP API, 登录机制修改)

3. 告警需求

a. 如果task运行失败，将会进行重试
b. 需要一个全新的告警模块，留好接口和短信集成。

评估：3.5Day(难点，需求不是太明确，和权限系统有关系？如何配置告警？)

4. 数据订阅

a. 添加和修改task的时候需要有From,to的信息。考虑采用datepicker控件
b. 提示信息中需要选择period类型：none，day，month，week

评估：1.5Day(难点：datepicker控件选择和使用，和OCSP系统集成)

**Comment by raindaywhu** [comment]
为支持多事件融合处理，修改了数据input的json 存储
  界面中"设置输入"中相关配置的需要能够支持配置多个数据类型，支持一至多条数据类型，典型的多个数据样例如下：
`{
    "props": [
        {
            "pname": "field.numbers",
            "pvalue": 17
        },
        {
            "pname": "topic",
            "pvalue": "betainput"
        },
        {
            "pname": "uniqKeys",
            "pvalue": "imsi"
        }
    ],
    "schema": [
        {
            "pname": "imsi",
            "ptype": "String"
        },
        {
            "pname": "bitholding5",
            "ptype": "String"
        }
    ],
    "sources": [
        {
            "pname": "3g",
            "delim": "|",
            "fields": [
		        {
		            "pname":"imsi",
		            "ptype":"String"
		        },
		        {
		            "pname":"lac",
		            "ptype":"String"
		        },
		        {
		            "pname":"cell",
		            "ptype":"String"
		        },
		        {
		            "pname":"bitholding3",
		            "ptype":"String"
		        }
            ],
			"userFields": [
			    {
			        "pname":"imsi",
			        "undefined":"on",
			        "pvalue":"(case when eventID in(3, 5, 7) then calledimsi when eventID in(8, 9, 10, 26) then (case when issmsalone=1 then callingimsi when issmsalone=2 then calledimsi else callingimsi end) else callingimsi end)"
			    },
			    {
			        "pname":"imei",
			        "undefined":"on",
			        "pvalue":"(case when eventID in(3, 5, 7) then calledimei when eventID in(8, 9, 10, 26) then (case when issmsalone=1 then callingimei when issmsalone=2 then calledimei else callingimei end) else callingimei end)"
			    },
			    {
			        "pname":"user_phone",
			        "undefined":"on",
			        "pvalue":"(case when eventID in(3, 5, 7) then calledphone when eventID in(8, 9, 10, 26) then (case when issmsalone=1 then callingphone when issmsalone=2 then calledphone else callingphone end) else callingphone end)"
			    }
			]
        }
    ]
}`
https://github.com/OCSP/OCSP_mainline/issues/13

**Comment by lishan** [comment]
重试次数和数据订阅已经提交。

#68 依赖于多事件需求，输出字段需要根据多事件schema中的字段和label pvalue中的字段选取，调研合适的component.

**Comment by DoraemonXX** [comment]
是否应该加一个多租户的开关，如果用户并不想用ldap用户或者多租户功能，admin用户的行为应该和当前版本一致，也就是可以做任何的操作

**Comment by DoraemonXX** [comment]
Dashboard需要显示的内容：

1. 任务的运行状态，可以用饼图表示，类似下面这样
![snip20170303_3](https://cloud.githubusercontent.com/assets/21124194/23533005/eb987516-ffe9-11e6-88df-3d155208109d.png)

2. 每个任务运行的时间统计，可以用柱状图表示，类似
![snip20170303_4](https://cloud.githubusercontent.com/assets/21124194/23533048/25699194-ffea-11e6-9d15-70687e88a8bf.png)

3. 每个任务丢掉数据和处理数据量大统计，可以用柱状图表示，类似下面这种，x轴是任务id，柱子表示累计数据量
![snip20170303_5](https://cloud.githubusercontent.com/assets/21124194/23533200/21f4c640-ffeb-11e6-9628-1dc14f1157d3.png)
每个柱子点进去是一个曲线图，x轴表示时间，y轴表示数据的变化，类似
![snip20170303_2](https://cloud.githubusercontent.com/assets/21124194/23533316/ff9f3ca0-ffeb-11e6-881d-d05a03ecad8f.png)

4. 事件的数量，可以用柱状图或者饼图，表示每个task需要处理的事件数据

5. 内存需求比例，例如下图，x轴表示任务id，y轴表示需要的内存，通过配置的Driver memory和Executor memory总合计算
![snip20170303_6](https://cloud.githubusercontent.com/assets/21124194/23533681/2b270090-ffee-11e6-9537-40bdb8139966.png)



@biggeng 看一下以上的这些是非合理，还有没有什么补充的，多谢

**Comment by DoraemonXX** [comment]
多租户登录的时候，要先验证ldap用户，在验证操作系统用户，最后验证ocsp数据库中用户；修改ocsp默认的用户为ocspadmin。

**Comment by lishan** [comment]
1. 多流输入的情况下，输出字段可以提示填入输入字段和标签的名字。
2. 多租户
3. Dashboard

**Comment by lishan** [comment]
所有的代码都已经提交，告警不涉及前台开发，用其他issue track
