### ISSUE TITLE
stream_task 在系统异常后，状态可能与实际状态不一致

### ISSUE THREAD

**Issue by raindaywhu** [OCSP/OCSP_mainline#77]
当集群都挂掉或者MainFrame 异常，再次启动时数据库中的状态依旧是RUNING，可能此时SPARK也是从异常中恢复， 需要进行状态的判断。

通过在STREAM_TASK表中记录applicationID，MainFrame启动时进行状态的检查，保证异常恢复后的状态。

**Comment by DoraemonXX** [comment]
此问题在https://github.com/OCSP/OCSP_mainline/issues/59中统一解决
