### ISSUE TITLE
规则配置热更新

### ISSUE THREAD

**Issue by biggeng** [OCSP/OCSP_mainline#79]
当用户通过界面或者API更新（添加或者删除）一个事件时，不需要重启spark streaming作业能够完成热更新。

**Comment by DoraemonXX** [comment]
在每次执行event之前都从数据库STREAM_EVENT表中获取最新的数据

**Comment by DoraemonXX** [comment]
测试用例：
测试准备，生成测试数据，bitholding7这个字段随机生成1-10的数字
1. 在webUI创建一个event，过滤条件为bitholding7='5'，输出的topic为kafka的output1，启动作业流

2. 通过消费output1观察输出的数据，bitholding7字段的值都是5，不停止作业流，更改过滤条件为3

3. 通过消费output1观察输出的数据，bitholding7字段的值都是3

4. 启动一个新的event，过滤条件为bitholding7='6'，输出的topic为kafka的output2，不停止作业流，通过消费output2观察输出的结果数据，bitholding7字段的值都是6

@biggeng 看一下以上的测试内容是否符合需求多谢

**Comment by DoraemonXX** [comment]
目前已经满足需求
