### ISSUE TITLE
所有数据库表的id改为int类型

### ISSUE THREAD

**Issue by DoraemonXX** [OCSP/OCSP_mainline#8]
所有数据库表的id改为int类型，且自动递增

**Comment by biggeng** [comment]
做完数据库改造后，建议生成一个.sql脚本，把这个脚本包在发布包中，用户可以直接通过这个脚本快速构建数据库。

**Comment by DoraemonXX** [comment]
@biggeng @GalvinYang 
更新数据库初始化脚本bin/init.sql
