### ISSUE TITLE
[Bug]没有设置heartbeat会导致异常

### ISSUE THREAD

**Issue by DoraemonXX** [OCSP/OCSP_mainline#90]
如果heartbeat设置为空会导致类型转换失败，建议增加空值校验

![snip20170328_5](https://cloud.githubusercontent.com/assets/21124194/24385135/e9a50bc4-139a-11e7-88ce-01f5a30c9ae1.png)

**Comment by raindaywhu** [comment]
heartbeat只有在RUNNING状态才会检查，当设置进程RUNNING之前先更新一次hearbeat，即可避免读取到空值的情况。
