### ISSUE TITLE
[BUG] Wrong displayment in subscribing output frequency column （month sector）

### ISSUE THREAD

**Issue by ArthurDong** [OCSP/OCSP_mainline#92]
https://cloud.githubusercontent.com/assets/19412214/24386654/6171047a-13a3-11e7-83b3-04af678ef098.png
the available time should be ranged from 1-31 instead of 10-39 in the typing bar, fatal error may appear.
ps. RED represent for invalid time, while blue stand for validated.

**Comment by ArthurDong** [comment]
![image](https://cloud.githubusercontent.com/assets/19412214/24386654/6171047a-13a3-11e7-83b3-04af678ef098.png)
the available time should be ranged from 1-31 instead of 10-39 in the typing bar, fatal error may appear.
ps. **RED** represent for invalid time, while **blue** stand for validated.

**Comment by DoraemonXX** [comment]
@lishan please fix this, thanks.
