### ISSUE TITLE
没有对于MainFrame进程异常退出做任何处理

### ISSUE THREAD

**Issue by DoraemonXX** [OCSP/OCSP_mainline#93]
如果发生issue #90  的情况，MainFrame进程会异常退出，定时器就会结束，这样导致对任务的状态无法监控，考虑这种场景如何处理

**Comment by raindaywhu** [comment]
MainFrame退出时 捕获异常，在异常信息表中输出一条异常信息。

**Comment by raindaywhu** [comment]
@DoraemonXX  @biggeng  当mysql 数据库异常时，当前行为同上， 在异常表中输出一条异常信息退出。

是否需要捕获所有mysql异常，mysql异常无法连接时也不退出？

**Comment by raindaywhu** [comment]
当mysql 异常时，StreamApp 会异常退出， MainFrame会假死。 这种情况的行为应当是系统的管理配置功能无法使用，但是StreamApp仍旧可以继续运行。

**Comment by biggeng** [comment]
How about to add HA for MainFrame and mysql database? @DoraemonXX @raindaywhu

**Comment by raindaywhu** [comment]
mysql 主要用以存储系统中stream的配置信息以及异常其他收集的统计信息。当mysql异常时， 系统中的Stream以及MainFrame不应当退出，此时只影响系统管理功能不可用。
目前修正后的行为： mysql 退出后，MainFrame 以及 Stream均不会退出，继续执行，当mysql恢复后，系统管理功能恢复正常。
