### ISSUE TITLE
[Bug]登录界面无法显示logo

### ISSUE THREAD

**Issue by biggeng** [OCSP/OCSP_mainline#95]
用最新版的开发包安装，启动后，界面logo无法显示。
![wechatimg16](https://cloud.githubusercontent.com/assets/8189833/24388522/e282ec22-13ad-11e7-9438-b16011b7cb6c.jpeg)

**Comment by lishan** [comment]
查看了后台，缺少web/dist/images文件夹，看一下新的build会不会有这样的问题

**Comment by DoraemonXX** [comment]
编译没有打进去，不是程序bug
