### ISSUE TITLE
[Enhancement]仪表盘中的运行状态不需要显示过多无用的状态

### ISSUE THREAD

**Issue by biggeng** [OCSP/OCSP_mainline#99]
很多状态是一个瞬时状态，建议不用在饼图中显示。

**Comment by DoraemonXX** [comment]
Done.

Thanks @lishan 

![snip20170330_8](https://cloud.githubusercontent.com/assets/21124194/24491145/814afaec-1558-11e7-8077-d2bfea06640e.png)
